name: 💿 extension
on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    name: ⬣ ESLint & Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout Repository
        uses: actions/checkout@v4.1.6

      - id: setup-bun
        name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - id: install-bun
        name: Bun Install
        run: |
          bun install

      - id: typecheck
        name: Checking Typescript Error
        run: |
          bun run typecheck

      - id: linter
        name: Linter check
        run: |
          bun run lint

      - id: build-extension
        name: Build extension
        env:
          SITE_DOMAIN: ${{ secrets.SITE_DOMAIN }}
        run: |
          cd apps/extension
          bun run build

      - id: zip-extension
        name: Zip extension
        run: |
          cd apps/extension
          bun run release

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/extension.zip
          asset_name: extension.zip
          asset_content_type: application/zip
